apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lidar-worker-hpa
  namespace: workloadc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lidar-worker
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lidar-master-hpa
  namespace: workloadc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lidar-master
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50