apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
  name: workloadc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidar-master
  namespace: workloadc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: lidar-master
  template:
    metadata:
      labels:
        run: lidar-master
    spec:
      containers:
        - name: lidar-master
          image: debnera/warehouse_master:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: KAFKA_INPUT_TOPIC
              value: "grid_master_input"
            - name: KAFKA_VALIDATE_TOPIC
              value: "grid_master_validate"
            - name: KAFKA_SERVERS
              value: "130.233.96.30:10001"
            - name: VERBOSE
              value: "TRUE"
            - name: VISUALIZE
              value: "TRUE"
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: lidar-master
  namespace: workloadc
  labels:
    run: lidar-master
spec:
  ports:
    - port: 80
  selector:
    run: lidar-master