global:
  scrape_interval: 5s
scrape_configs:

  # KAFKA BROKER SCRAPERS
  - job_name: kafka
    metrics_path: /metrics
    static_configs:
      - targets:
          - kafka_broker_1:11001

  # KAFKA BROKER SCRAPERS
  - job_name: yolo
    metrics_path: /
    static_configs:
      - targets:
          - yolo_validator:8000
