apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
  name: workloadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-consumer
  namespace: workloadb
spec:
  replicas: 2
  selector:
    matchLabels:
      run: yolo-consumer
  template:
    metadata:
      labels:
        run: yolo-consumer
    spec:
      containers:
        - name: yolo-consumer
          image: debnera/ov_yolo:0.3-test
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: YOLO_MODEL
              value: "yolov8n"
            - name: KAFKA_INPUT_TOPIC
              value: "yolo_input"
            - name: KAFKA_OUTPUT_TOPIC
              value: "yolo_output"
            - name: KAFKA_SERVERS
              value: "130.233.96.30:10001"
          #resources:
          #  limits:
          #    cpu: 1000m
          #  requests:
          #    cpu: 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-consumer
  namespace: workloadb
  labels:
    run: yolo-consumer
spec:
  ports:
    - port: 80
  selector:
    run: yolo-consumer